# Generated by Django 6.0.4 on 2026-05-02 13:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('english', 'English'), ('hindi', 'Hindi')], max_length=10)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('is_free', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['language', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upi_id', models.CharField(help_text='Apna UPI ID (e.g. yourname@paytm)', max_length=100)),
                ('upi_name', models.CharField(default='Smart Typing Test', help_text='Payment mein dikhne wala naam', max_length=100)),
                ('site_domain', models.CharField(default='http://127.0.0.1:8000', help_text='Production mein apna domain (e.g. https://yoursite.com)', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_key', models.CharField(choices=[('week', '1 Week'), ('month', '1 Month'), ('3month', '3 Months'), ('6month', '6 Months')], help_text='Plan ka unique ID — change mat karna', max_length=20, unique=True)),
                ('plan_name', models.CharField(help_text="Display name, e.g. '1 Week Plan'", max_length=100)),
                ('price', models.PositiveIntegerField(help_text='Plan ki price sirf rupees mein (e.g. 9, 19, 49, 99)')),
                ('duration_days', models.PositiveIntegerField(help_text='Kitne din ka access milega (e.g. 7, 30, 90, 180)')),
                ('description', models.CharField(blank=True, help_text="Short description, e.g. '7 din ka access'", max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='False karo to yeh plan payment page pe nahi dikhega')),
                ('is_popular', models.BooleanField(default=False, help_text='True karo to POPULAR badge dikhega')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Kaun sa plan pehle dikhega — chota number = pehle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['display_order', 'price'],
            },
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_resets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('base_amount', models.IntegerField()),
                ('unique_paise', models.IntegerField()),
                ('unique_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('transaction_ref', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending — Verify Karo'), ('approved', 'Approved ✅'), ('expired', 'Expired ⏰'), ('rejected', 'Rejected ❌')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, max_length=20, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
